const FormFieldData = [
  {
    field_name: "Text_Field",
    field_type: "text_box",
    label: "Text Field",
    placeholder: "Enter Text Field",
    Validation: true,
    is_show_to_listing: true,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^[A-Za-z ]+$",
        errorMsg: "Text field must contain only letters and spaces",
      },
      {
        type: "pattern",
        value: "^.{3,}$",
        errorMsg: "Text field must have at least 3 characters",
      },
    ],
  },
  {
    field_name: "Email",
    field_type: "email",
    label: "email",
    placeholder: "Enter Email Field",
    Validation: true,
    is_show_to_listing: true,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[A-Za-z]{2,}$",
        errorMsg: "Invalid email format",
      },
      {
        type: "pattern",
        value: "^.{6,}$",
        errorMsg: "Email must be at least 6 characters long",
      },
    ],
  },
  {
    field_name: "Password",
    field_type: "password",
    label: "Password",
    placeholder: "Enter a strong password",
    Validation: true,
    is_show_to_listing: true,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*?&]).+$",
        errorMsg:
          "Password must contain letters, numbers, and a special character",
      },
      {
        type: "pattern",
        value: "^.{6,15}$",
        errorMsg: "Password must be between 6 and 15 characters",
      },
    ],
  },
  {
    field_name: "Text_Area",
    field_type: "textarea",
    label: "Text Area",
    placeholder: "Enter your Text area",
    Validation: true,
    is_show_to_listing: true,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^.{10,}$",
        errorMsg: "Text Area must be at least 10 characters long",
      },
    ],
  },
  {
    field_name: "Number",
    field_type: "number",
    label: "Number Field",
    placeholder: "Enter your number field",
    Validation: true,
    is_show_to_listing: true,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^[6-9]\\d{9}$",
        errorMsg: "Enter valid 10-digit Indian number",
      },
      {
        type: "pattern",
        value: "^\\d+$",
        errorMsg: "number should contain only digits",
      },
    ],
  },
  {
    field_name: "Date",
    field_type: "date",
    label: "Date field",
    placeholder: "Select your date",
    Validation: true,
    is_show_to_listing: false,
    is_show_to_form: false,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$",
        errorMsg: "Date must be in YYYY-MM-DD format",
      },
    ],
  },
  {
    field_name: "Radio",
    field_type: "radio",
    label: "Radio",
    options: [
      {
        label: "Option 1",
        value: "option1",
      },
      {
        label: "Option 2",
        value: "option2",
      },
    ],
    dataSourceType: "static",
    placeholder: "Radio Field",
    Validation: true,
    is_show_to_listing: true,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^.+$",
        errorMsg: "Please select an option",
      },
    ],
  },
  {
    field_name: "Select_Field",
    field_type: "select",
    label: "Select Field",
    options: [
      {
        label: "Option 1",
        value: "option1",
      },
      {
        label: "Option 2",
        value: "option2",
      },
    ],
    dataSourceType: "static",
    placeholder: "Select Field",
    Validation: false,
    validationRules: [],
    is_show_to_listing: false,
    is_show_to_form: false,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
  },
  {
    field_name: "Checkbox",
    field_type: "checkbox",
    label: "Checkbox_Field",
    options: [
      {
        label: "Option 1",
        value: "option1",
      },
      {
        label: "Option 2",
        value: "option2",
      },
    ],
    dataSourceType: "static",
    placeholder: "Checkbox Field",
    Validation: false,
    validationRules: [],
    is_show_to_listing: false,
    is_show_to_form: false,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
  },
  {
    field_name: "Time_Field",
    field_type: "time",
    label: "Time Field",
    placeholder: "Select time",
    Validation: true,
    is_show_to_listing: true,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^([01]\\d|2[0-3]):([0-5]\\d)$",
        errorMsg: "Please enter time in HH:MM format (24-hour)",
      },
    ],
  },
  {
    field_name: "Custom_Time",
    field_type: "text",
    label: "Custom Time Field",
    placeholder: "Enter time (e.g. 02:30 PM)",
    Validation: true,
    is_show_to_listing: false,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
    validationRules: [
      {
        type: "pattern",
        value: "^(0[1-9]|1[0-2]):([0-5]\\d)\\s?(AM|PM)$",
        errorMsg: "Please enter time in hh:mm AM/PM format",
      },
    ],
  },
  {
    field_name: "File_Upload",
    field_type: "file",
    label: "Upload File",
    placeholder: "Choose a file",
    Validation: false,
    validationRules: [],
    is_show_to_listing: false,
    is_show_to_form: true,
    is_active: true,
    is_hidden: false,
    is_show_to_view: true,
    is_searchable: false,
  },
];

export default FormFieldData;
